### ISSUE TITLE
error when running quartet sampling

### ISSUE THREAD

**Issue by kmeusemann** [FePhyFoFum/quartetsampling#12]
Hi all, 

I have several datasets on which I run the quartetsampling. On one I ge constantly an error:
ile ":..quartet_sampling.py", line 369, in <module>
    main()
  File "...quartet_sampling.py", line 317, in main
    pool.map(process_replicate_raxml_lrt, replicates)
  File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: '...QuartetSampling/RAxML_info.tts.QS1.3' does not exist

Can anyone help me here? the other datasets are running nicely.... (with the same python library). My original command:

python3 /PATHTO/quartet_sampling.py --tree TREEFILE.tre --align alignment.phy --threads 12 --reps 100 --results-dir ./results/ --engine raxml --data-type amino --lnlike 2 --partitions PARTITIONFILE_raxml_format.txt --result-prefix TEST --verbose --calc-qdstats

### 

In addition: I would love to run it with IQtree and or raxML-ng but this constantly crashes als with the test datasets and more important also always with a provided partition file. I know that iqtree is experimental but is there any progress on this?

Thanks in advance! 
Karen

**Comment by kmeusemann** [comment]
Hi again,

here again a bit more output before the error occured:
it seems like the same error when they failed trying iqtree... - a file not found error:

multiprocessing.pool.RemoteTraceback:

"""

Traceback (most recent call last):

File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker

result = (True, func(*args, **kwds))

File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar

return list(map(*args))

File "/PATHTO/quartetsampling/pysrc/rep_data.py", line 619, in process_replicate_raxml_lrt

raise RuntimeError("'{}' does not exist".format(lpath))

RuntimeError: '/PATHTO/QuartetSampling/RAxML_info.tts.QS29.140' does not exist

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/PATHTO/quartet_sampling.py", line 369, in <module>

main()

File "/PATHTO/quartet_sampling.py", line 317, in main

pool.map(process_replicate_raxml_lrt, replicates)

File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 268, in map

return self._map_async(func, iterable, mapstar, chunksize).get()

File "/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 657, in get

raise self._value

RuntimeError: '/...PATHTO.../QuartetSampling/RAxML_info.tts.QS29.140' does not exist

**Comment by kmeusemann** [comment]
Hi all,

t would be gret if anyone of the developters cound comment since I suppose it is appreciated when the tool is used ;). Also it would be nice to hear if this is currently still improved/developed (with e.g. iqtree) or if this was simply a single project which is finished.

Many thanks, Karen

**Comment by jbpease** [comment]
You patience during this global emergency is appreciated.  

The project is still under a active development.

When using the software in partition mode, this error could result from one of partitions having insuffient data. (See page 3 of the manual.)  Does the same data set run without partitioning?

**Comment by kmeusemann** [comment]
Dear James,

thanks for the quick reply. Of course this situation is everywhere not good, however I appreciate your quick reply.

Trying to answer your question: yes and no:
1) Partitioned model: one time the dataset finished succesfully with partitioned mode & using raxml! However, when trying an alternative tree topology and i) trying it a second time with the same tree it finished before successfully, it crashed.  So it might be reasoned on the ?randomly drawn? replicates, however, hard to track for me the reason. (It could be an issue with possibly insufficient data - however it would not explain why it one time finished successfully and a second time crashed)
2) In a first trial running it unpartitioned and using as model the best selected model which was LG4X, it crashed (same error as decribed above). I am currently trying it again , trying now the second best model and the same dataset - still running. If it finishes would be great but not ideal since I do not understand why it would crash with LG4X. 

Thanks, Karen

**Comment by kmeusemann** [comment]
PS: very useful to know thats still under atcive developement! Looking fw to further versions!

**Comment by jbpease** [comment]
From your description, it sounds like the Raxml problems are from the known limitation above, where if you have insufficient data in *any* partition for a particular quartet Raxml and IQtree will error out.  This is because it requires data for all the partitions.  If you turn on --ignore-errors this can bypass this and will ignore these errors. This is a limitation to QS under the partitioned mode that we are still working out.  As you say, it would explain why it only appears sometimes.

For the example above, is there a log file associated with RAxML_info.tts.QS29.140? (Usually RAxML_log.tts.QS29.140) that would say why raxml was stopping.

Same for IQtree, if you could send a log file for the IQtree where it errors (usually a log file associated with the highest number replicate) that might help me diagnose the issue.  Curious to see why the unpartitioned Lg4x not working. You're also welcome to directly email me the log files or even the data files and I can try to troubleshoot.

**Comment by kmeusemann** [comment]
Hi James,

Unfortunately, I tried so many runs with little difference that I did not keep everything, Also, there is no log file, (but also no folder "QuartetSampling" - (maybe a temporary folder?). I will try now another couple of test-runs, try to keep/find log files by making a folder "QuartetSampling" prior to the runs, and then let you know as soon as possible what happens - and send you log files if I can find them. 

Thanks a lot!! Karen

**Comment by kmeusemann** [comment]
Hi James,

1) I reran the partitioned analyses: unfortunately there is no logfile RaxML_log.tts.XX: Obviously the script creates a working directory QuartetSampling? which is then deleted in the end? I only saw this during the runs before they crashed, inside there were no RAxML files, only temp* files. I will send you the only log file from the system that I have. Also  th--ignore-errors sis not help. Will sned the command and log file via email

2) RAxML unpartitioned with LG4X: crashed again: same thing.

Maybe there is a way that the QuartetSampling temporary folder is not deleted? 

3) the unpartitioned run with iqtree and LG4X finished successfully!

Best, Karen

**Comment by kmeusemann** [comment]
PS: just send ou the output via email. Thanks for taking care, 
Happy Easter! Karen

**Comment by duanyuj** [comment]
Hi James

I encountered some problems, I ask for your help，as follows

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/quartetsampling-master/pysrc/rep_data.py", line 764, in process_replicate_raxmlng_lrt
    stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/raxml-ng/bin'

How can i fix it？

Best wishes
Yujie

**Comment by kmeusemann** [comment]
Hi James,

just to let you know: 
1) the issue is indeed solved when running all runs separately in subdirectories (before I was just parsing the results in separate folders). So all PARTITIONED runs (with RAxML) finished successfully. the error occurs when runs are running in parallel because only one QuartetSampling folder is created and maybe then files are deleted during the run that cause other runs to crash.  It would be I think very helpful if
- either in the manual/README an additional note will be added e added, that each run should run in a single subfolder (meaning the job script must be startet in a single separate subfolder since there the temp. "QuartetSampling" folder is created (and deleted afterwards) 
- or the script is rewritten in such a way that the step "make temporary folder" has a unique name for each run, but I dig not into the script enough to jusge if this would be easily possible.

2) shall I also test/rerun the LG4X RAXML unpartitioned run? in the way above to test if this was the same issue?

Best, Karen

**Comment by kmeusemann** [comment]
PS: I also now tried  in separate folders
- the partitioned ones but with iqtree and
- the unpartitioned with raxml and LG4X
both crashed. I will send you tests and output files + the temporary fils in the "QuartetSamling folder via email: I will not use them but hope for you and your team its useful to fix these issues in future versions. Looking fw to future versions as well :)
Best, Karen

**Comment by duanyuj** [comment]
> PS: I also now tried in separate folders
> 
> * the partitioned ones but with iqtree and
> * the unpartitioned with raxml and LG4X
>   both crashed. I will send you tests and output files + the temporary fils in the "QuartetSamling folder via email: I will not use them but hope for you and your team its useful to fix these issues in future versions. Looking fw to future versions as well :)
>   Best, Karen

Hi Karen

I have encountered some problems as shown below, do you know how to solve it? Thank you very much！

Traceback (most recent call last):
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds))
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar return list(map(*args))
File "/root/quartetsampling-master/pysrc/rep_data.py", line 764, in process_replicate_raxmlng_lrt
stderr=subprocess.PIPE)
File "/usr/local/lib/python3.7/subprocess.py", line 800, in init restore_signals, start_new_session)
File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/raxml-ng/bin'

Best wishes

Yujie
