### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by kcart7** [FePhyFoFum/quartetsampling#8]
Hello, 

I'm getting a new error when I try to run quartetsampling now:

processing node 1/91
not calculating qc for tip child '26fullgene' of the root (qc is 1.0, as for all tips).

processing node 2/91 | average node time 0.02 seconds | est. remaining time 1.80 seconds
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/local/cluster/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/local/cluster/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/raid1/home/bpp/home/local/bin/quartetsampling/pysrc/rep_data.py", line 506, in process_replicate_raxml2lk
    stderr=subprocess.PIPE)
  File "/local/cluster/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/local/cluster/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py", line 318, in <module>
    main()
  File "/raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py", line 274, in main
    pool.map(process_replicate_raxml2lk, replicates)
  File "/local/cluster/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/local/cluster/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
PermissionError: [Errno 13] Permission denied

Here's the command:
python3.5 /raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py -t topologyonly_trimalgt0.2_polyanddiptree_nomisalign.tre -a trimalgt0.2_polyanddip_nomisaligngenes_norogues_forSVD.phy -N 100 -T 1 -L 2 -g gene_partition_file.txt --ignore-errors -o test

Maybe something to do with the version of python I'm using? I'm working on a cluster, and we have 2.7 and 3.5 installed. I tried with 2.7 but got a totally different error. 

Thank you!

**Comment by jbpease** [comment]
From the error message, I think this issue may be due to the server configuration, specifically in regards to the python multiprocessing module:
https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

**Comment by SimonGreenhill** [comment]
I wonder if the cluster user does not have read/write permissions on quartetsampling's default temporary directory?

**Comment by jbpease** [comment]
Are you still having issues with this?
